name: "Build"

on: [push, pull_request]

jobs:
  Matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Matrix
        id: matrix
        uses: Invicton-Labs/terraform-module-testing-configuration/matrix@dev
        with:
          minimum_tf_version: '0.13.0'

      - name: Output Matrix
        run: |
          echo "Strategy: ${{ steps.matrix.outputs.strategy }}"

    outputs:
      strategy: ${{ steps.matrix.outputs.strategy }}
          
  Test:
    needs: [Matrix]
    strategy: ${{ fromJSON(needs.Matrix.outputs.strategy)}}
    runs-on: ${{ matrix.runs-on }}
    container: ${{ matrix.container }}
    steps:
      - name: Run Tests
        id: tests
        uses: Invicton-Labs/terraform-module-testing-configuration/test@dev
        with:
          testing_path: tester
          
  # This job just waits for all other jobs to pass. We have it here
  # so our branch protection rule can reference a single job, instead
  # of needing to list every matrix value of every job above.
  Passed:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
    - name: Mark tests as passed
      run: echo "🎉"