name: "CICD_v2"

on: [push, pull_request]

jobs:
  Linux:
    strategy:
      fail-fast: false
      matrix:
        image_name: ["alpine", "redhat/ubi8-minimal", "redhat/ubi9-minimal", "fedora", "ubuntu"]
        image_tag: ["latest"]
        shell: ["/bin/sh"]
        tf_version: ["1.2.0"]
        include:
          # # Extra tags per image
          # - image_name: "ubuntu"
          #   image_tag: "latest"
          #   shell: "/bin/bash"
          # - image_name: "ubuntu"
          #   image_tag: "latest"
          #   shell: "/bin/dash"
            
          # - image_name: "ubuntu"
          #   image_tag: "18.04"
          #   shell: "/bin/bash"
          # - image_name: "ubuntu"
          #   image_tag: "18.04"
          #   shell: "/bin/dash"

          # - image_name: "ubuntu"
          #   image_tag: "20.04"
          #   shell: "/bin/bash"
          # - image_name: "ubuntu"
          #   image_tag: "20.04"
          #   shell: "/bin/dash"
            
          # - image_name: "ubuntu"
          #   image_tag: "22.04"
          #   shell: "/bin/bash"
          # - image_name: "ubuntu"
          #   image_tag: "22.04"
          #   shell: "/bin/dash"

          # Installation commands per image name
          - image_name: "alpine"
            tf_install: wget https://releases.hashicorp.com/terraform/{TF_VERSION}/terraform_{TF_VERSION}_linux_amd64.zip && unzip terraform_{TF_VERSION}_linux_amd64.zip && mv terraform /usr/bin/terraform
          - image_name: "redhat/ubi8-minimal"
            tf_install: yum install -y yum-utils && yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo && yum -y install terraform={TF_VERSION}
          - image_name: "redhat/ubi9-minimal"
            tf_install: yum install -y yum-utils && yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo && yum -y install terraform={TF_VERSION}
          - image_name: "fedora"
            tf_install: dnf install -y dnf-plugins-core && dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo && dnf -y install terraform={TF_VERSION}
          - image_name: "ubuntu"
            tf_install: curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add - && apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" && apt-get update && apt-get install terraform={TF_VERSION}

    runs-on: ubuntu-latest
    container:
      image: "${{ matrix.image_name }}:${{ matrix.image_tag }}"
      volumes:
        - ${{ github.workspace }}:/workspace
    
    steps:
      - name: Matrix Values
        run: |
          echo "image_name: ${{ matrix.image_name }}"
          echo "image_tag: ${{ matrix.image_tag }}"
          echo "shell: ${{ matrix.shell }}"
          echo "tf_version: ${{ matrix.tf_version }}"

      - name: Install Terraform
        run: |
          _cmd=$(echo '${{ matrix.tf_install }}' | sed 's/{TF_VERSION}/${{ matrix.tf_version }}/g')
          echo "$_cmd"
          eval "$_cmd"

      - name: Terraform Init
        working-directory: /workspace
        run: terraform init

      - name: Terraform Plan
        working-directory: /workspace
        run: terraform plan